version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "📦 Installing prerequisites"
      - git fetch --unshallow || echo "Repo already has full history"
      - pip install -r requirements.txt
      - ls -la .git || echo ".git folder not found!"
  build:
    commands:
      - echo "🚀 Running static file upload"
      - chmod +x upload_static_assets.sh
      - echo "Checking environment: $ENVIRONMENT_TYPE"
      - [ "$ENVIRONMENT_TYPE" == "BETA" ] && BUCKET_NAME=s3-static-test-upload || [ "$ENVIRONMENT_TYPE" == "PROD" ] && BUCKET_NAME=s3-test-static-artbuck || { echo "Unknown environment type! Please set ENVIRONMENT_TYPE to BETA or PROD."; exit 1; } && echo "Uploading static files to s3://$BUCKET_NAME/static/" && aws s3 sync static/ s3://$BUCKET_NAME/static/ --acl public-read

artifacts:
  files:
    - '**/*'

