version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "📦 Installing prerequisites"
      - git fetch --unshallow || echo "Repo already has full history"
      - pip install -r requirements.txt
      - ls -la .git || echo ".git folder not found!"
  build:
    commands:
      - echo "🚀 Running static file upload"
      - chmod +x upload_static_assets.sh
      - echo "Checking environment $ENVIRONMENT_TYPE"
      - |
        # Set the correct bucket name based on ENVIRONMENT_TYPE
        if [ "$ENVIRONMENT_TYPE" == "BETA" ]; then
          BUCKET_NAME="s3-static-test-upload"
        elif [ "$ENVIRONMENT_TYPE" == "PROD" ]; then
          BUCKET_NAME="s3-test-static-artbuck"
        else
          echo "Unknown environment type! Please set ENVIRONMENT_TYPE to BETA or PROD."
          exit 1
        fi
        echo "Uploading static files to s3://$BUCKET_NAME/static/"
      - echo "Preparing comparison directory..."
      - mkdir -p changed_files
      - mkdir -p previous_static
      - echo "Downloading previously deployed static files from S3..."
      - aws s3 sync s3://$BUCKET_NAME/static/ previous_static/ || echo "No previous static files"
      - echo "Comparing current static/ with previous_static/..."
      - rsync -rc --compare-dest=../previous_static/ static/ changed_files/
      - echo "Uploading only changed files to S3..."
      - aws s3 cp changed_files/ s3://$BUCKET_NAME/static/ --recursive --acl public-read
artifacts:
  files:
    - '**/*'
