version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "📦 Installing prerequisites"
      - git fetch --unshallow || echo "Repo already has full history"
      - echo "🧠 Current working dir: $(pwd)"
      - ls -la
      - echo "Checking for .git directory"
      - ls -la .git || echo ".git folder not found!"
  build:
    commands:
      - echo "🚀 Running static file upload for PROD"
      - chmod +x upload_static_assets.sh
      - ./upload_static_assets.sh prod
artifacts:
  files:
    - '**/*'
