version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "🐍 Python 3.12 environment setup complete"

  
  build:
    commands:
      - echo "🚀 Running static asset upload script"
      - chmod +x upload_static_assets.sh
      - ./upload_static_assets.sh prod

artifacts:
  files:
    - '**/*'

