version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "📦 Installing prerequisites"
      - git fetch --unshallow || echo "Repo already has full history"
      - pip install -r requirements.txt
      - ls -la .git || echo ".git folder not found!"
  build:
    commands:
      - echo "🚀 Running static file upload for PROD"
      - chmod +x upload_static_assets.sh
      - aws s3 sync static/ s3://s3-static-test-upload/static/ --acl public-read
        # - ./upload_static_assets.sh prod
        # - python manage.py runserver 
artifacts:
  files:
    - '**/*'
